### PR TITLE
Add a confirmation modal when starting or restarting a plan or starting cutover + Fix error reporting on confirm modal when archiving a plan.

### LINKED ISSUE #624: Add a confirm dialog when clicking Start/Cutover/Restart on a plan
We don't have a confirmation dialog when starting a plan or initiating cutover on a warm migration plan. This feels like an oversight to me, what do you think @vconzola? A simple button click kicks off such a huge long-running thing, it would be annoying as hell to do it by accident.

### PR DESCRIPTION
**Pull request by mturley**
Closes #624.

This PR:
* Adds a confirmation modal when clicking the Start or Cutover buttons on a plan, or the Restart kebab action.
* Removes the weird `errorContainerRef` we had to use to put errors starting a plan above the plans table, now that they live in the confirm modal.
* Refactors the confirm modal when archiving a plan to use our common `ConfirmModal` so it will report errors in the POST request properly. Note that this only applies to the POST itself, a backend failure to complete the archive process will instead result in a status condition on the plan.

## Confirm modals of various flavors:

Starting a cold plan:
Screen Shot 2021-09-30 at 3 51 30 PM

Starting a warm plan:
Screen Shot 2021-10-04 at 3 52 46 PM

Starting cutover on a warm plan:
Screen Shot 2021-09-30 at 4 09 25 PM

Restarting a cold plan:
Screen Shot 2021-09-30 at 3 53 25 PM

Restarting a warm plan:
Screen Shot 2021-09-30 at 3 54 56 PM

## Error reporting in the modal:

Screen Shot 2021-09-30 at 4 05 34 PM

Screen Shot 2021-09-30 at 4 06 06 PM

### CODE REVIEW

**Comment by mturley** [comment]
Note to self: "VMs included in the migration plan will remain powered on until cutover is started" is not accurate if the VMs were already powered off by the user. Need to update that phrasing so it makes sense in that case.

@seanforyou23 If you and Vince decide on different text here, feel free to push to this and merge while I'm on PTO if you need to unblock the Archive state stuff.

File: src/app/Plans/components/MigrateOrCutoverButton.tsx [hunk 1]
```diff
@@ -1,71 +1,58 @@
...
 }: IMigrateOrCutoverButtonProps) => {
   const history = useHistory();
-  const onMigrationStarted = (migration: IMigration) => {
-    history.push(`/plans/${migration.spec.plan.name}`);
+  const onMigrationStarted = () => {
+    toggleConfirmModal();
+    history.push(`/plans/${plan.metadata.name}`);
   };
   const createMigrationMutation = useCreateMigrationMutation(onMigrationStarted);
-  const setCutoverMutation = useSetCutoverMutation();
```
Comment (mturley) [inline src/app/Plans/components/MigrateOrCutoverButton.tsx:30]: This change makes the page navigate into the migration details when clicking Cutover, which wasn't happening before. But I think it's good to make that consistent with starting the migration. Not sure if you agree @vconzola

**Comment by fdupont-redhat** [comment]
@mperezco, what do you think of this change? While I see the value of reminding that the VMs will be shutdown during cold migration and cutover, it seems to complexify the experience.

**Comment by mperezco** [comment]
> @mperezco, what do you think of this change? While I see the value of reminding that the VMs will be shutdown during cold migration and cutover, it seems to complexify the experience.

I agree that adds one step to the process but it also prevents accidentally shutting down VMs. 
Please let's keep it.

**Review by fdupont-redhat — APPROVED** [review]
Following @mperezco opinion.

**Comment by mperezco** [comment]
> Following @mperezco opinion.

Thanks!

**Comment by mturley** [comment]
Waiting to merge this until I have a chance to review the text with @vconzola . I was winging it :)

**Comment by mturley** [comment]
Updated the text of the "starting a warm plan" confirmation. Ready to merge now.

**Comment by vconzola** [comment]
@mturley Does the screenshot show the correct modal text for restarting incremental copies? I think it should be the same as starting incremental copies.

**Comment by mturley** [comment]
@vconzola sorry, I forgot to update the screenshots. It is the same:
Screen Shot 2021-10-05 at 10 58 25 AM

**Comment by vconzola** [comment]
@mturley Cool. Thanks.

File: src/app/Plans/components/MigrateOrCutoverConfirmModal.tsx [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+      title={`${verb} ${noun}?`}
+      body={
+        <TextContent>
+          <Text>
+            {verb} the {noun} for plan &quot;{plan.metadata.name}&quot;?
+          </Text>
+          <Text>
+            {action === 'cutover' || !plan.spec.warm
+              ? 'VMs included in the migration plan will be shut down.'
+              : 'VM data will be copied incrementally until cutover migration. To start cutover, click the button on the Plans page.'}{' '}
```
Comment (apinnick) [inline src/app/Plans/components/MigrateOrCutoverConfirmModal.tsx:38]: `To start cutover, click the button`

Will the button be clear to the user? It's not clear to me. If the button has a label, like "Cutover", I suggest that use it: "click the Cutover button ..."

File: src/app/Plans/components/MigrateOrCutoverConfirmModal.tsx [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+            See the product documentation for more information.
+          </Text>
+        </TextContent>
+      }
+      confirmButtonText={action === 'cutover' ? 'Cutover' : verb}
+      errorText={`Could not ${verb.toLowerCase()} ${noun}`}
```
Comment (apinnick) [inline src/app/Plans/components/MigrateOrCutoverConfirmModal.tsx:44]: `Could not $`: Recommend changing to "Cannot $". It is generally better to use present tense.

File: src/app/Plans/components/PlanActionsDropdown.tsx [hunk 4]
```diff
@@ -219,37 +231,28 @@ export const PlanActionsDropdown: React.FunctionComponent<IPlansActionDropdownPr
...
+              <ListItem>All migration history and metadata are cleaned up and discarded.</ListItem>
+              <ListItem>Migration logs are deleted.</ListItem>
+              <ListItem>
+                The plan can no longer be edited or restarted, but it can be viewed.
+              </ListItem>
+            </List>
+          </TextContent>
+        }
+        confirmButtonText="Archive"
+        errorText="Could not archive plan"
```
Comment (apinnick) [inline src/app/Plans/components/PlanActionsDropdown.tsx:254]: Recommend changing to "Cannot archive plan"

File: src/app/Plans/components/MigrateOrCutoverConfirmModal.tsx [hunk 5]
```diff
@@ -0,0 +1,49 @@
...
+  isOpen,
+  toggleOpen,
+  mutateFn,
+  mutateResult,
+  plan,
+  action,
+}: IMigrateOrCutoverConfirmModalProps) => {
+  const verb = action === 'restart' ? 'Restart' : 'Start';
+  const noun =
+    action === 'cutover' ? 'cutover' : plan.spec.warm ? 'incremental copies' : 'migration';
```
Comment (apinnick) [inline src/app/Plans/components/MigrateOrCutoverConfirmModal.tsx:22]: @vconzola 
I have a question about "incremental copies". Isn't this called "stage migration" in other parts of the UI? I think that is how the Migration Plan wizard refers to the step before cutover and that is the term I have used in the documentation.

File: src/app/Plans/components/MigrateOrCutoverConfirmModal.tsx [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+      body={
+        <TextContent>
+          <Text>
+            {verb} the {noun} for plan &quot;{plan.metadata.name}&quot;?
+          </Text>
+          <Text>
+            {action === 'cutover' || !plan.spec.warm
+              ? 'VMs included in the migration plan will be shut down.'
+              : 'VM data will be copied incrementally until cutover migration. To start cutover, click the button on the Plans page.'}{' '}
+            See the product documentation for more information.
```
[the remark this answers is not in the document]
Comment (mturley) [reply src/app/Plans/components/MigrateOrCutoverConfirmModal.tsx:39]: The link in the help menu is already there. Will remove from this PR, and open a followup PR to remove elsewhere.

File: src/app/Plans/components/PlanActionsDropdown.tsx (hunk 4 above)
Comment (mturley) [reply src/app/Plans/components/PlanActionsDropdown.tsx:254]: https://github.com/konveyor/forklift-ui/issues/790
